SHELL := /bin/bash

all:
	gst squareRootOfList.text
	
	gst HelloWorld.text
	
	gst Numbers.text
	
	gst Character.text
	
	gst dict.text
	
	gst sortedCollect.text
	
	gst orderedCollect.text
	
	gst string.text