SHELL := /bin/bash

all:
	gst squareRootOfList.text
	
	gst HelloWorld.text
	
	gst p3_Numbers.text
	
	gst p3_Character.text
	
	gst p3_dict.text
	
	gst p3_sortedCollect.text
	
	gst p3_orderedCollect.text
	
	gst p3_string.text